#!/usr/bin/env bash

# Get Branch of Evo to Compile
if [ -z "$1" ] || [ -z "$2" ]
then
	echo -e "Usage: bundle-compiler <git-repository> <bundle-name>"
	exit
fi

echo -e "\n================================="
echo -e "EvolutionSDK Phar Bundle Compiler"
echo -e "            By KellyLSB          "
echo -e "=================================\n"

# Checkout the repo and prepare for compile
rm -Rf src
git clone $1 src
rm -Rf src/.git*

# Create the build dir
rm -Rf build
mkdir build

# CLI Interface
echo "<?php echo 'This is an EvolutionSDK Bundle and cannot be run from the command line';" > src/cli.php

# Web Interface
echo "<?php
include_once __DIR__.\"/_bundle.php\";
__HALT_COMPILER();" > src/web.php

# Start Compiling the Phar
echo "<?php ini_set('phar.readonly', 0);

\$root = realpath(__DIR__);
\$srcRoot = \$root.\"/src\";
\$buildRoot = \$root.\"/build\";

\$phar = new Phar(\$buildRoot . '/$2.phar', 0, '$2.phar');
\$phar->compressFiles(Phar::GZ);
\$phar->setSignatureAlgorithm (Phar::SHA1);

\$phar->buildFromDirectory(\$srcRoot);
\$phar->setDefaultStub('cli.php', 'web.php');
\$phar = null;" | /usr/bin/env php

# Done Compiling the Phar File
echo "" > "build/built-$(date +%Y-%m-%d_%H%M)"
echo -e "\nDone Compiling...\n"
